# Generated by Django 5.2.1 on 2025-05-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_disciplinaporcurso_carga_horaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.AlterField(
            model_name='disciplinaporcurso',
            name='periodo',
            field=models.CharField(max_length=100, verbose_name='Carga horaria'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.DeleteModel(
            name='PeriodoCurso',
        ),
    ]
