# Generated by Django 5.2.1 on 2025-05-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_turno_alter_disciplinaporcurso_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno'),
        ),
    ]
