# Generated by Django 5.2.1 on 2025-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_matricula_turma_alter_turma_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='avaliacao_tipo',
            field=models.CharField(default='', max_length=100, verbose_name='Tipo de avaliação'),
        ),
        migrations.AlterField(
            model_name='disciplinaporcurso',
            name='periodo',
            field=models.CharField(max_length=100, verbose_name='periodo'),
        ),
    ]
