# Generated by Django 5.2.1 on 2025-05-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_avaliacao_avaliacao_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliacao_tipo',
        ),
        migrations.AddField(
    model_name='avaliacao',
    name='tipoavaliacao',
    field=models.ForeignKey(
        on_delete=models.CASCADE,
        to='app.TipoAvaliacao',
        default=1,  # <-- Coloque o ID de um registro válido
    ),
    preserve_default=False,
),
    ]
