# Generated by Django 5.2.1 on 2025-05-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_avaliacao_avaliacao_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='tipoavaliacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoavaliacao'),
        ),
    ]
