# Generated by Django 5.2.1 on 2025-05-18 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_avaliacao_tipoavaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
                ('num_matricula', models.CharField(max_length=20, verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
            bases=('app.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
                ('formacao', models.CharField(max_length=100, verbose_name='Formação')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
            bases=('app.pessoa',),
        ),
        migrations.AddField(
            model_name='matricula',
            name='num_matricula',
            field=models.CharField(default='', max_length=100, verbose_name='Número da matrícula'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipoavaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoavaliacao'),
        ),
    ]
