# Generated by Django 5.2.1 on 2025-05-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_aluno_professor_matricula_num_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipoavaliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoavaliacao'),
        ),
    ]
