# Generated by Django 5.2.1 on 2025-05-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_disciplina_professor_alter_avaliacao_tipoavaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
    ]
