# Generated by Django 5.2.1 on 2025-05-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_disciplina_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
    ]
